#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# Generate bpi_msgs/msg/*.msg from schemas/0.2/.
#
# Generated rather than hand-written so the ROS interface cannot drift away from
# the schemas. tools/check-consistency.sh re-runs this and fails the build if the
# committed output differs, which is the same discipline the requirement
# checklist is held to.
#
# ---------------------------------------------------------------------------
# THE DESIGN DECISION, WHICH IS THE WHOLE POINT OF THIS FILE
#
# Every message carries `string canonical_json`: the exact RFC 8785 bytes the
# signature was computed over, verbatim.
#
# The obvious design — map each JSON field to a ROS field and let the type system
# carry the message — CANNOT WORK for anything signed. A signature is over
# specific bytes. Decode those bytes into a ROS message, publish it, and
# re-encode on the far side, and you get bytes that differ in key order, in
# number formatting, or in which absent-versus-null distinction survived. The
# signature then fails, and the receiving node concludes it is being attacked
# when it is only being helped.
#
# There is a second, sharper reason. ROS IDL cannot express three things BPI
# relies on: a nullable field (prevHash is string-or-null, and null at seq 0 is
# LEGAL and MEANINGFUL), a conditional shape (if/then/else on applicability), or
# absent-as-distinct-from-empty. A generator that flattened those would produce
# messages that look conformant and are not.
#
# So the decoded fields below are CONVENIENCE, for routing, logging and display.
# The canonical_json is the message. Any node that verifies a signature, checks a
# chain, or forwards a token to another party must use canonical_json and must
# not rebuild it from the decoded fields.
# ---------------------------------------------------------------------------
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SCHEMAS = ROOT / "schemas" / "0.2"
OUT = pathlib.Path(__file__).resolve().parent / "bpi_msgs" / "msg"

# JSON Schema scalar -> ROS 2 IDL. Anything not here is carried in
# canonical_json only, which is the honest outcome rather than a lossy guess.
SCALARS = {
    "string": "string",
    "integer": "int64",
    "number": "float64",
    "boolean": "bool",
}


def ros_type(prop: dict) -> str | None:
    """The ROS type for a scalar property, or None if it is not representable.

    A nullable scalar returns None on purpose. ROS has no null, and mapping it to
    an empty string would erase the difference between "seq 0, legitimately no
    predecessor" and "predecessor omitted by mistake" — which is precisely the
    distinction [R-S-020] turns on.
    """
    t = prop.get("type")
    if isinstance(t, list):
        return None  # nullable or union: not representable, see the docstring
    if t in SCALARS:
        return SCALARS[t]
    if t == "array":
        item = prop.get("items", {})
        inner = SCALARS.get(item.get("type")) if isinstance(item.get("type"), str) else None
        return f"{inner}[]" if inner else None
    if "$ref" in prop and prop["$ref"].endswith("Timestamp"):
        return "string"
    if "const" in prop:
        return "string"
    return None


def camel_to_snake(s: str) -> str:
    """maxPower_kW -> max_power_kw, not max_power_k_w.

    The schemas use a name_unit convention — maxPower_kW, abortToSafe_ms,
    declaredPfd_dBW_m2 — where everything after the first underscore is a unit
    symbol whose capitalisation is SI, not camelCase. Splitting those on case
    boundaries mangles them. So: camel-split the leading name, and take each
    underscore-separated unit token as a whole.
    """
    head, _, tail = s.partition("_")
    out = []
    for i, c in enumerate(head):
        if c.isupper() and i and not head[i - 1].isupper():
            out.append("_")
        out.append(c.lower())
    name = "".join(out)
    return f"{name}_{tail.lower()}" if tail else name


def generate(schema_path: pathlib.Path) -> tuple[str, str]:
    schema = json.loads(schema_path.read_text())
    title = schema.get("title") or schema_path.stem
    props = schema.get("properties", {})
    required = set(schema.get("required", []))

    lines = [
        "# SPDX-License-Identifier: Apache-2.0",
        "#",
        f"# {title}",
        "#",
    ]
    for chunk in (schema.get("description") or "").split(". "):
        if chunk.strip():
            lines.append(f"# {chunk.strip().rstrip('.')}.")
    lines += [
        "#",
        "# GENERATED by sdk/ros2/generate-msgs.py. Do not edit.",
        "#",
        "# canonical_json is the message. The fields below it are decoded copies for",
        "# routing and display; rebuilding the JSON from them will not reproduce the",
        "# bytes the signature covers. See the header of the generator.",
        "",
        "string canonical_json",
        "",
    ]

    skipped = []
    for name, prop in props.items():
        if not isinstance(prop, dict):
            continue  # `true` schemas inherited from the envelope
        rt = ros_type(prop)
        field = camel_to_snake(name)
        if rt is None:
            skipped.append(name)
            continue
        note = "" if name in required else "  # optional in the schema"
        lines.append(f"{rt} {field}{note}")

    if skipped:
        lines += [
            "",
            "# Present in the schema, carried only in canonical_json because ROS IDL",
            "# cannot represent them without changing their meaning:",
        ]
        lines += [f"#   {n}" for n in skipped]

    return f"{title}.msg", "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    written, drifted = 0, []

    for schema_path in sorted(SCHEMAS.glob("*.schema.json")):
        if schema_path.name == "common.schema.json":
            continue  # definitions, not a message
        name, body = generate(schema_path)
        target = OUT / name
        if check:
            if not target.exists() or target.read_text() != body:
                drifted.append(name)
        else:
            target.write_text(body)
        written += 1

    if check:
        if drifted:
            print(f"  ros2 messages have drifted from the schemas: {', '.join(drifted)}")
            return 1
        print(f"  {written} ros2 messages match the schemas")
        return 0

    print(f"  wrote {written} messages to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
